steps:
 # Docker Build
 - name: 'gcr.io/cloud-builders/docker'
 args: ['build', '-t', 'us-central1-docker.pkg.dev/devops-2024-425717/cloud-run-storage-example/api:${SHORT_SHA}','.']
 # Docker push to Google Artifact Registry
 - name: 'gcr.io/cloud-builders/docker'
 args: ['push', 'us-central1-docker.pkg.dev/devops-2024-425717/cloud-run-storage-example/api_:${SHORT_SHA}']
# Store images in Google Artifact Registry
images:
 - us-central1-docker.pkg.dev/devops-2024-425717/cloud-run-storage-example/api:${SHORT_SHA}
